name: Unzip Project Files

on:
  push:
    paths:
      - '**.zip'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  unzip-and-commit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Configure Git
        run: |
          git config --global user.name "GitHub Action"
          git config --global user.email "action@github.com"

      - name: Unzip project_upload.zip
        run: |
          if [ -f "project_upload.zip" ]; then
            echo "Found project_upload.zip, unzipping..."
            unzip -o project_upload.zip
            echo "Unzip complete. Removing zip file..."
            rm project_upload.zip
            
            echo "Committing changes..."
            git add .
            git commit -m "Auto-unzip project files"
            git push
          else
            echo "project_upload.zip not found."
          fi
