# File        : docker-compose.yaml
# Author      : Chandan Sheikder
# Email       : chandan@bit.edu.cn
# Phone       : +8618222390506
# Affiliation : Beijing Institute of Technology (BIT)
# Date        : 2026-03-23
#
version: '3'

services:
  simulation:
    build: .
    volumes:
      - .:/catkin_ws
    environment:
      - DISPLAY=${DISPLAY}
      - QT_X11_NO_MITSHM=1
    network_mode: host
    privileged: true
    stdin_open: true
    tty: true
    command: /bin/bash -c "cd /catkin_ws && catkin_make && source devel/setup.bash && roslaunch hybrid_navigation master_swarm.launch"
