// Generated by gencpp from file hybrid_navigation/SceneComplexity.msg
// DO NOT EDIT!


#ifndef HYBRID_NAVIGATION_MESSAGE_SCENECOMPLEXITY_H
#define HYBRID_NAVIGATION_MESSAGE_SCENECOMPLEXITY_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>

namespace hybrid_navigation
{
template <class ContainerAllocator>
struct SceneComplexity_
{
  typedef SceneComplexity_<ContainerAllocator> Type;

  SceneComplexity_()
    : header()
    , scene_type()
    , complexity_score(0.0)
    , obstacle_density(0.0)
    , trap_detected(false)  {
    }
  SceneComplexity_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , scene_type(_alloc)
    , complexity_score(0.0)
    , obstacle_density(0.0)
    , trap_detected(false)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _scene_type_type;
  _scene_type_type scene_type;

   typedef float _complexity_score_type;
  _complexity_score_type complexity_score;

   typedef float _obstacle_density_type;
  _obstacle_density_type obstacle_density;

   typedef uint8_t _trap_detected_type;
  _trap_detected_type trap_detected;





  typedef boost::shared_ptr< ::hybrid_navigation::SceneComplexity_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::hybrid_navigation::SceneComplexity_<ContainerAllocator> const> ConstPtr;

}; // struct SceneComplexity_

typedef ::hybrid_navigation::SceneComplexity_<std::allocator<void> > SceneComplexity;

typedef boost::shared_ptr< ::hybrid_navigation::SceneComplexity > SceneComplexityPtr;
typedef boost::shared_ptr< ::hybrid_navigation::SceneComplexity const> SceneComplexityConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::hybrid_navigation::SceneComplexity_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::hybrid_navigation::SceneComplexity_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::hybrid_navigation::SceneComplexity_<ContainerAllocator1> & lhs, const ::hybrid_navigation::SceneComplexity_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.scene_type == rhs.scene_type &&
    lhs.complexity_score == rhs.complexity_score &&
    lhs.obstacle_density == rhs.obstacle_density &&
    lhs.trap_detected == rhs.trap_detected;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::hybrid_navigation::SceneComplexity_<ContainerAllocator1> & lhs, const ::hybrid_navigation::SceneComplexity_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace hybrid_navigation

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::hybrid_navigation::SceneComplexity_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::hybrid_navigation::SceneComplexity_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::hybrid_navigation::SceneComplexity_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::hybrid_navigation::SceneComplexity_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::hybrid_navigation::SceneComplexity_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::hybrid_navigation::SceneComplexity_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::hybrid_navigation::SceneComplexity_<ContainerAllocator> >
{
  static const char* value()
  {
    return "f871fe5893f973c3015c98df1108df3b";
  }

  static const char* value(const ::hybrid_navigation::SceneComplexity_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xf871fe5893f973c3ULL;
  static const uint64_t static_value2 = 0x015c98df1108df3bULL;
};

template<class ContainerAllocator>
struct DataType< ::hybrid_navigation::SceneComplexity_<ContainerAllocator> >
{
  static const char* value()
  {
    return "hybrid_navigation/SceneComplexity";
  }

  static const char* value(const ::hybrid_navigation::SceneComplexity_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::hybrid_navigation::SceneComplexity_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# Custom message for scene complexity analysis\n"
"Header header\n"
"string scene_type\n"
"float32 complexity_score\n"
"float32 obstacle_density\n"
"bool trap_detected\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
;
  }

  static const char* value(const ::hybrid_navigation::SceneComplexity_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::hybrid_navigation::SceneComplexity_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.scene_type);
      stream.next(m.complexity_score);
      stream.next(m.obstacle_density);
      stream.next(m.trap_detected);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct SceneComplexity_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::hybrid_navigation::SceneComplexity_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::hybrid_navigation::SceneComplexity_<ContainerAllocator>& v)
  {
    if (false || !indent.empty())
      s << std::endl;
    s << indent << "header: ";
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "scene_type: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.scene_type);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "complexity_score: ";
    Printer<float>::stream(s, indent + "  ", v.complexity_score);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "obstacle_density: ";
    Printer<float>::stream(s, indent + "  ", v.obstacle_density);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "trap_detected: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.trap_detected);
  }
};

} // namespace message_operations
} // namespace ros

#endif // HYBRID_NAVIGATION_MESSAGE_SCENECOMPLEXITY_H
