// Generated by gencpp from file hybrid_navigation/TetherStatus.msg
// DO NOT EDIT!


#ifndef HYBRID_NAVIGATION_MESSAGE_TETHERSTATUS_H
#define HYBRID_NAVIGATION_MESSAGE_TETHERSTATUS_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>
#include <geometry_msgs/Point.h>
#include <geometry_msgs/Point.h>

namespace hybrid_navigation
{
template <class ContainerAllocator>
struct TetherStatus_
{
  typedef TetherStatus_<ContainerAllocator> Type;

  TetherStatus_()
    : header()
    , length(0.0)
    , tension(0.0)
    , max_length(0.0)
    , snag_detected(false)
    , base_station_pos()
    , robot_pos()  {
    }
  TetherStatus_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , length(0.0)
    , tension(0.0)
    , max_length(0.0)
    , snag_detected(false)
    , base_station_pos(_alloc)
    , robot_pos(_alloc)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef float _length_type;
  _length_type length;

   typedef float _tension_type;
  _tension_type tension;

   typedef float _max_length_type;
  _max_length_type max_length;

   typedef uint8_t _snag_detected_type;
  _snag_detected_type snag_detected;

   typedef  ::geometry_msgs::Point_<ContainerAllocator>  _base_station_pos_type;
  _base_station_pos_type base_station_pos;

   typedef  ::geometry_msgs::Point_<ContainerAllocator>  _robot_pos_type;
  _robot_pos_type robot_pos;





  typedef boost::shared_ptr< ::hybrid_navigation::TetherStatus_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::hybrid_navigation::TetherStatus_<ContainerAllocator> const> ConstPtr;

}; // struct TetherStatus_

typedef ::hybrid_navigation::TetherStatus_<std::allocator<void> > TetherStatus;

typedef boost::shared_ptr< ::hybrid_navigation::TetherStatus > TetherStatusPtr;
typedef boost::shared_ptr< ::hybrid_navigation::TetherStatus const> TetherStatusConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::hybrid_navigation::TetherStatus_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::hybrid_navigation::TetherStatus_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::hybrid_navigation::TetherStatus_<ContainerAllocator1> & lhs, const ::hybrid_navigation::TetherStatus_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.length == rhs.length &&
    lhs.tension == rhs.tension &&
    lhs.max_length == rhs.max_length &&
    lhs.snag_detected == rhs.snag_detected &&
    lhs.base_station_pos == rhs.base_station_pos &&
    lhs.robot_pos == rhs.robot_pos;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::hybrid_navigation::TetherStatus_<ContainerAllocator1> & lhs, const ::hybrid_navigation::TetherStatus_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace hybrid_navigation

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::hybrid_navigation::TetherStatus_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::hybrid_navigation::TetherStatus_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::hybrid_navigation::TetherStatus_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::hybrid_navigation::TetherStatus_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::hybrid_navigation::TetherStatus_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::hybrid_navigation::TetherStatus_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::hybrid_navigation::TetherStatus_<ContainerAllocator> >
{
  static const char* value()
  {
    return "7e63c602ea59303866ec3d11befde5db";
  }

  static const char* value(const ::hybrid_navigation::TetherStatus_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x7e63c602ea593038ULL;
  static const uint64_t static_value2 = 0x66ec3d11befde5dbULL;
};

template<class ContainerAllocator>
struct DataType< ::hybrid_navigation::TetherStatus_<ContainerAllocator> >
{
  static const char* value()
  {
    return "hybrid_navigation/TetherStatus";
  }

  static const char* value(const ::hybrid_navigation::TetherStatus_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::hybrid_navigation::TetherStatus_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# Custom message for tether status\n"
"Header header\n"
"float32 length\n"
"float32 tension\n"
"float32 max_length\n"
"bool snag_detected\n"
"geometry_msgs/Point base_station_pos\n"
"geometry_msgs/Point robot_pos\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Point\n"
"# This contains the position of a point in free space\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
;
  }

  static const char* value(const ::hybrid_navigation::TetherStatus_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::hybrid_navigation::TetherStatus_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.length);
      stream.next(m.tension);
      stream.next(m.max_length);
      stream.next(m.snag_detected);
      stream.next(m.base_station_pos);
      stream.next(m.robot_pos);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct TetherStatus_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::hybrid_navigation::TetherStatus_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::hybrid_navigation::TetherStatus_<ContainerAllocator>& v)
  {
    if (false || !indent.empty())
      s << std::endl;
    s << indent << "header: ";
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "length: ";
    Printer<float>::stream(s, indent + "  ", v.length);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "tension: ";
    Printer<float>::stream(s, indent + "  ", v.tension);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "max_length: ";
    Printer<float>::stream(s, indent + "  ", v.max_length);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "snag_detected: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.snag_detected);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "base_station_pos: ";
    Printer< ::geometry_msgs::Point_<ContainerAllocator> >::stream(s, indent + "  ", v.base_station_pos);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "robot_pos: ";
    Printer< ::geometry_msgs::Point_<ContainerAllocator> >::stream(s, indent + "  ", v.robot_pos);
  }
};

} // namespace message_operations
} // namespace ros

#endif // HYBRID_NAVIGATION_MESSAGE_TETHERSTATUS_H
